node_addr: http://213.239.193.208:9053
http_client_timeout_duration_secs: 5
chain_sync_starting_height: 912500
log4rs_yaml_path: conf/log4rs.yaml
chain_cache_db_path: ./tmp/chain
kafka_address: "kafka:9092"
blocks_topic: "blocks_topic"
tx_topic: "tx_topic"